import Sidebar from "@/components/sidebar"
import './globals.css'
import { Figtree } from 'next/font/google'
import SupabaseProvider from "@/providers/supabase"
import { UserContextProvider } from "@/hooks/useUser"
import ModalProvider from "@/providers/modal"
import ToasterProvider from "@/providers/toaster"
import getSongsByUID from "@/actions/get-songs-by-uid"
import Player from "@/components/player"

const font = Figtree({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const songs = await getSongsByUID();
  
  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterProvider />
        <SupabaseProvider>
          <UserContextProvider>
            <ModalProvider />
            <Sidebar songs={songs}>{children}</Sidebar>
            <Player />
          </UserContextProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
